-- Kinesis Application - Tumbling Window

CREATE OR REPLACE STREAM "MAVG_1_SQL_STREAM" (ISIN VARCHAR(16), Volume INTEGER, Trades INTEGER, EndPrice REAL);
CREATE OR REPLACE STREAM "MAVG_5_SQL_STREAM" (ISIN VARCHAR(16), Volume INTEGER, Trades INTEGER, EndPrice REAL);

CREATE OR REPLACE PUMP "MAVG_1_PUMP" AS INSERT INTO "MAVG_1_SQL_STREAM"
SELECT STREAM ISIN, SUM("TradedVolume") AS Volume, SUM("NumberOfTrades") as Trades, Max("EndPrice")
FROM "SOURCE_SQL_STREAM_001"
GROUP BY ISIN, STEP("SOURCE_SQL_STREAM_001".ROWTIME BY INTERVAL '1' MINUTE);

CREATE OR REPLACE PUMP "MAVG_5_PUMP" AS INSERT INTO "MAVG_5_SQL_STREAM"
SELECT STREAM ISIN, SUM("TradedVolume") AS Volume, SUM("NumberOfTrades") as Trades, Max("EndPrice")
FROM "SOURCE_SQL_STREAM_001"
GROUP BY ISIN, STEP("SOURCE_SQL_STREAM_001".ROWTIME BY INTERVAL '5' MINUTE);

-- Kinesis Application - Stagger window

CREATE OR REPLACE STREAM "MAVG_1_SQL_STREAM" (ISIN VARCHAR(16), Volume INTEGER, Trades INTEGER, EndPrice REAL);
CREATE OR REPLACE STREAM "MAVG_5_SQL_STREAM" (ISIN VARCHAR(16), Volume INTEGER, Trades INTEGER, EndPrice REAL);

CREATE OR REPLACE PUMP "MAVG_1_PUMP" AS
INSERT INTO "MAVG_1_SQL_STREAM"
SELECT STREAM ISIN, SUM("TradedVolume") AS Volume, SUM("NumberOfTrades") as Trades, AVG("EndPrice")
FROM "SOURCE_SQL_STREAM_001"
WINDOWED BY STAGGER (
    PARTITION BY ISIN RANGE INTERVAL '1' MINUTE);

CREATE OR REPLACE PUMP "MAVG_5_PUMP" AS
INSERT INTO "MAVG_5_SQL_STREAM"
SELECT STREAM ISIN, SUM("TradedVolume") AS Volume, SUM("NumberOfTrades") as Trades, AVG("EndPrice")
FROM "SOURCE_SQL_STREAM_001"
WINDOWED BY STAGGER (
    PARTITION BY ISIN RANGE INTERVAL '5' MINUTE);
